---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=Greb1605*!
      - FOUNDRY_USERNAME=dugreb@gmail.com
      - FOUNDRY_ADMIN_KEY=atropos
      - FOUNDRY_LICENSE_KEY=VXBV-KRV4-SWTM-TKWJ-FASW-RAFX
      - FOUNDRY_VERSION=12.331
      - FOUNDRY_RELEASE_URL=https://foundryvtt.com/releases/download?build=331&platform=linux
      - CONTAINER_VERBOSE=true
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
